// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: bet.proto

package betpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EventId       string                 `protobuf:"bytes,3,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Odds          float64                `protobuf:"fixed64,5,opt,name=odds,proto3" json:"odds,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Payout        float64                `protobuf:"fixed64,7,opt,name=payout,proto3" json:"payout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bet) Reset() {
	*x = Bet{}
	mi := &file_bet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bet) ProtoMessage() {}

func (x *Bet) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bet.ProtoReflect.Descriptor instead.
func (*Bet) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{0}
}

func (x *Bet) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Bet) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Bet) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *Bet) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Bet) GetOdds() float64 {
	if x != nil {
		return x.Odds
	}
	return 0
}

func (x *Bet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Bet) GetPayout() float64 {
	if x != nil {
		return x.Payout
	}
	return 0
}

type CreateBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBetRequest) Reset() {
	*x = CreateBetRequest{}
	mi := &file_bet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBetRequest) ProtoMessage() {}

func (x *CreateBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBetRequest.ProtoReflect.Descriptor instead.
func (*CreateBetRequest) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateBetRequest) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type CreateBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateBetResponse) Reset() {
	*x = CreateBetResponse{}
	mi := &file_bet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateBetResponse) ProtoMessage() {}

func (x *CreateBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateBetResponse.ProtoReflect.Descriptor instead.
func (*CreateBetResponse) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{2}
}

func (x *CreateBetResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type GetBetByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetByIDRequest) Reset() {
	*x = GetBetByIDRequest{}
	mi := &file_bet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetByIDRequest) ProtoMessage() {}

func (x *GetBetByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetByIDRequest.ProtoReflect.Descriptor instead.
func (*GetBetByIDRequest) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{3}
}

func (x *GetBetByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetBetByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetByIDResponse) Reset() {
	*x = GetBetByIDResponse{}
	mi := &file_bet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetByIDResponse) ProtoMessage() {}

func (x *GetBetByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetByIDResponse.ProtoReflect.Descriptor instead.
func (*GetBetByIDResponse) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{4}
}

func (x *GetBetByIDResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type GetBetsByUserIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetsByUserIDRequest) Reset() {
	*x = GetBetsByUserIDRequest{}
	mi := &file_bet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetsByUserIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetsByUserIDRequest) ProtoMessage() {}

func (x *GetBetsByUserIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetsByUserIDRequest.ProtoReflect.Descriptor instead.
func (*GetBetsByUserIDRequest) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{5}
}

func (x *GetBetsByUserIDRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetBetsByUserIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bets          []*Bet                 `protobuf:"bytes,1,rep,name=bets,proto3" json:"bets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBetsByUserIDResponse) Reset() {
	*x = GetBetsByUserIDResponse{}
	mi := &file_bet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBetsByUserIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBetsByUserIDResponse) ProtoMessage() {}

func (x *GetBetsByUserIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBetsByUserIDResponse.ProtoReflect.Descriptor instead.
func (*GetBetsByUserIDResponse) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{6}
}

func (x *GetBetsByUserIDResponse) GetBets() []*Bet {
	if x != nil {
		return x.Bets
	}
	return nil
}

type UpdateBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBetRequest) Reset() {
	*x = UpdateBetRequest{}
	mi := &file_bet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBetRequest) ProtoMessage() {}

func (x *UpdateBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBetRequest.ProtoReflect.Descriptor instead.
func (*UpdateBetRequest) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateBetRequest) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type UpdateBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bet           *Bet                   `protobuf:"bytes,1,opt,name=bet,proto3" json:"bet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateBetResponse) Reset() {
	*x = UpdateBetResponse{}
	mi := &file_bet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateBetResponse) ProtoMessage() {}

func (x *UpdateBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateBetResponse.ProtoReflect.Descriptor instead.
func (*UpdateBetResponse) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateBetResponse) GetBet() *Bet {
	if x != nil {
		return x.Bet
	}
	return nil
}

type DeleteBetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBetRequest) Reset() {
	*x = DeleteBetRequest{}
	mi := &file_bet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBetRequest) ProtoMessage() {}

func (x *DeleteBetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBetRequest.ProtoReflect.Descriptor instead.
func (*DeleteBetRequest) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteBetRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteBetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteBetResponse) Reset() {
	*x = DeleteBetResponse{}
	mi := &file_bet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteBetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteBetResponse) ProtoMessage() {}

func (x *DeleteBetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_bet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteBetResponse.ProtoReflect.Descriptor instead.
func (*DeleteBetResponse) Descriptor() ([]byte, []int) {
	return file_bet_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteBetResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_bet_proto protoreflect.FileDescriptor

const file_bet_proto_rawDesc = "" +
	"\n" +
	"\tbet.proto\x12\x03bet\"\xa5\x01\n" +
	"\x03Bet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x19\n" +
	"\bevent_id\x18\x03 \x01(\tR\aeventId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x12\n" +
	"\x04odds\x18\x05 \x01(\x01R\x04odds\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x16\n" +
	"\x06payout\x18\a \x01(\x01R\x06payout\".\n" +
	"\x10CreateBetRequest\x12\x1a\n" +
	"\x03bet\x18\x01 \x01(\v2\b.bet.BetR\x03bet\"/\n" +
	"\x11CreateBetResponse\x12\x1a\n" +
	"\x03bet\x18\x01 \x01(\v2\b.bet.BetR\x03bet\"#\n" +
	"\x11GetBetByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"0\n" +
	"\x12GetBetByIDResponse\x12\x1a\n" +
	"\x03bet\x18\x01 \x01(\v2\b.bet.BetR\x03bet\"1\n" +
	"\x16GetBetsByUserIDRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"7\n" +
	"\x17GetBetsByUserIDResponse\x12\x1c\n" +
	"\x04bets\x18\x01 \x03(\v2\b.bet.BetR\x04bets\".\n" +
	"\x10UpdateBetRequest\x12\x1a\n" +
	"\x03bet\x18\x01 \x01(\v2\b.bet.BetR\x03bet\"/\n" +
	"\x11UpdateBetResponse\x12\x1a\n" +
	"\x03bet\x18\x01 \x01(\v2\b.bet.BetR\x03bet\"\"\n" +
	"\x10DeleteBetRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"-\n" +
	"\x11DeleteBetResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcd\x02\n" +
	"\n" +
	"BetService\x12:\n" +
	"\tCreateBet\x12\x15.bet.CreateBetRequest\x1a\x16.bet.CreateBetResponse\x12=\n" +
	"\n" +
	"GetBetByID\x12\x16.bet.GetBetByIDRequest\x1a\x17.bet.GetBetByIDResponse\x12L\n" +
	"\x0fGetBetsByUserID\x12\x1b.bet.GetBetsByUserIDRequest\x1a\x1c.bet.GetBetsByUserIDResponse\x12:\n" +
	"\tUpdateBet\x12\x15.bet.UpdateBetRequest\x1a\x16.bet.UpdateBetResponse\x12:\n" +
	"\tDeleteBet\x12\x15.bet.DeleteBetRequest\x1a\x16.bet.DeleteBetResponseB'Z%muchway/bet_service/proto/betpb;betpbb\x06proto3"

var (
	file_bet_proto_rawDescOnce sync.Once
	file_bet_proto_rawDescData []byte
)

func file_bet_proto_rawDescGZIP() []byte {
	file_bet_proto_rawDescOnce.Do(func() {
		file_bet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_bet_proto_rawDesc), len(file_bet_proto_rawDesc)))
	})
	return file_bet_proto_rawDescData
}

var file_bet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_bet_proto_goTypes = []any{
	(*Bet)(nil),                     // 0: bet.Bet
	(*CreateBetRequest)(nil),        // 1: bet.CreateBetRequest
	(*CreateBetResponse)(nil),       // 2: bet.CreateBetResponse
	(*GetBetByIDRequest)(nil),       // 3: bet.GetBetByIDRequest
	(*GetBetByIDResponse)(nil),      // 4: bet.GetBetByIDResponse
	(*GetBetsByUserIDRequest)(nil),  // 5: bet.GetBetsByUserIDRequest
	(*GetBetsByUserIDResponse)(nil), // 6: bet.GetBetsByUserIDResponse
	(*UpdateBetRequest)(nil),        // 7: bet.UpdateBetRequest
	(*UpdateBetResponse)(nil),       // 8: bet.UpdateBetResponse
	(*DeleteBetRequest)(nil),        // 9: bet.DeleteBetRequest
	(*DeleteBetResponse)(nil),       // 10: bet.DeleteBetResponse
}
var file_bet_proto_depIdxs = []int32{
	0,  // 0: bet.CreateBetRequest.bet:type_name -> bet.Bet
	0,  // 1: bet.CreateBetResponse.bet:type_name -> bet.Bet
	0,  // 2: bet.GetBetByIDResponse.bet:type_name -> bet.Bet
	0,  // 3: bet.GetBetsByUserIDResponse.bets:type_name -> bet.Bet
	0,  // 4: bet.UpdateBetRequest.bet:type_name -> bet.Bet
	0,  // 5: bet.UpdateBetResponse.bet:type_name -> bet.Bet
	1,  // 6: bet.BetService.CreateBet:input_type -> bet.CreateBetRequest
	3,  // 7: bet.BetService.GetBetByID:input_type -> bet.GetBetByIDRequest
	5,  // 8: bet.BetService.GetBetsByUserID:input_type -> bet.GetBetsByUserIDRequest
	7,  // 9: bet.BetService.UpdateBet:input_type -> bet.UpdateBetRequest
	9,  // 10: bet.BetService.DeleteBet:input_type -> bet.DeleteBetRequest
	2,  // 11: bet.BetService.CreateBet:output_type -> bet.CreateBetResponse
	4,  // 12: bet.BetService.GetBetByID:output_type -> bet.GetBetByIDResponse
	6,  // 13: bet.BetService.GetBetsByUserID:output_type -> bet.GetBetsByUserIDResponse
	8,  // 14: bet.BetService.UpdateBet:output_type -> bet.UpdateBetResponse
	10, // 15: bet.BetService.DeleteBet:output_type -> bet.DeleteBetResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_bet_proto_init() }
func file_bet_proto_init() {
	if File_bet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_bet_proto_rawDesc), len(file_bet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_bet_proto_goTypes,
		DependencyIndexes: file_bet_proto_depIdxs,
		MessageInfos:      file_bet_proto_msgTypes,
	}.Build()
	File_bet_proto = out.File
	file_bet_proto_goTypes = nil
	file_bet_proto_depIdxs = nil
}
